version: '3'
services:
  phpfpm:
    container_name: phpfpm
    image: ginsen/php-fpm
    ports:
      - 3000:3000
    environment:
      - TIMEZONE=${TIMEZONE}
      - LOCALE=${LOCALE}
      - LANG=${LANG}
    volumes:
      - ./:/var/www/html
    command: php -S="0.0.0.0:3000" -t="/var/www/html"